---
- name: Install nginx on Ubuntu
  hosts: webserver
  become: yes

  tasks:
    - name: "Update apt cache"
      apt:
        update_cache: yes

    - name: "Install Nginx"
      package:
        name: "nginx"
        state: present

    - name: "Start Nginx"
      service:
        name: nginx
        state: started
        enabled: yes

    - name: "Change nginx file permissions"
      shell: "sudo chmod -R 755 /var/www/html & sudo chown -R ubuntu:ubuntu /var/www/html"