name: Deploy index.html to EC2

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      deploy_file: "index.html"
    steps:
      - name: Checkout the files
        uses: actions/checkout@v2
  
      - name: Deploy to EC2 instance
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SOURCE: "dist/$deploy_file"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ secrets.REMOTE_TARGET_DIR }}
          SCRIPT_AFTER: |
            echo "Deployed new index.html"
